### ISSUE TITLE
Instructions require electron installation

### ISSUE THREAD

**Issue by paul-brenner** [jeffisfast/doodle-elgato-light-controller#1]
After step 1 in the instrucitons should be 
`npm install electron`

Otherwise you receive this error.

`get sh: electron-forge: command not found`

Maybe I'm the only person alive doing this who didn't have electron installed.

**Comment by jeffisfast** [comment]
Thanks @paul-brenner .  I'll add to the instructions.  As mentioned in the README, this codebase is pretty rough and assumes a certain amount of experience.  Feel free to pass on any other feedback and I'll update accordingly.

**Comment by paul-brenner** [comment]
Thanks! I don't touch node very much so probably anyone who does wouldn't have needed to google what was going on.

Loving the global hotkey now that the change you made in issue 2 is working! Did you modify your instal to hide the dock icon or are you just less bothered than I am by extra icons in the dock? 

I may look into how to hide that dock icon and see how much effort it would take for someone without node experience... I suppose now is a good a time as any to gain some.

**Comment by jeffisfast** [comment]
I don't care for extra dock icons either!  I just added a function call that hides the app icon in a Mac OS dock.  Not sure how this manifests on Windows or Linux (or if it does anything) but feel free to pull the latest code and give it a try. @paul-brenner

**Comment by paul-brenner** [comment]
I love it! command-option-j is my new favorite shortcut. Fumbling to turn the light on in precious moments before a call is just a thing of the past now, I can't believe how happy this makes me.
