### ISSUE TITLE
After install, can't get menubar icon to respond to clicks

### ISSUE THREAD

**Issue by paul-brenner** [jeffisfast/doodle-elgato-light-controller#2]
I'm sure I'm just incompetent at working with electron apps like this and am missing something obvious. But when I start with `npm run start` the app launches into my menu bar, nice, but clicking on it doesn't do anything. I am just completely missing where I can do step 5 of the instructions `Once the program is running, click on the menu choice "IP Settings" and input your light's IP address`.

Realize the dev is probably busy, so will try to keep hunting for how I can diagnose what I'm doing wrong, but really don't know anything about electron apps and how to debug.

**Comment by jeffisfast** [comment]
Thanks @paul-brenner .  You definitely found a bug and I'm scratching my head wondering how this app ever worked.  My guess is that during development my code saved the IP address of my light which allowed the app to work.  On a new install, like yours, without that IP address cached the menu wouldn't display.  Please reclone the repository and try again.
